spring:
  datasource:
    common:
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 300000
        connection-timeout: 20000
        max-lifetime: 1200000
    tenant:
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 300000
        connection-timeout: 20000
        max-lifetime: 1200000
  config:
    # FrontEndのURL
    frontend-url-format: ${FRONTEND_URL_FORMAT}
    common:
      migration: db/migration/common
      testdata: db/testdata/common
    tenant:
      migration: db/migration/tenant
      testdata: db/testdata/tenant/{tenantKey}
  aws:
    secretsmanager:
      endpoint: http://localstack:4566
      region: us-east-1
      common: ${COMMON_SECRET}
      flyway: ${FLYWAY_SECRET}
      security: ${SECURITY_SECRET}
    s3:
      endpoint: http://localstack:4566
      region: us-east-1
      bucket-name: ${UPLOAD_BUCKET_NAME}
server:
  port: 8444
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: test1234
    key-store-type: PKCS12
    key-alias: tomcat
