name: "deploy bastion image"
concurrency:
  group: deploy-bastion-image-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
env:
  aws_region: "ap-northeast-1"

permissions:
  id-token: write
  contents: read

jobs:
  set-env:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    timeout-minutes: 10
    outputs:
      aws_region: ${{ env.aws_region }}
      env: ${{ github.ref_name }}
      short-env: ${{ github.ref_name == 'develop' && 'dev' || github.ref_name == 'production' && 'prod' || github.ref_name == 'staging' && 'stg' || 'dev' }}
    steps:
      - name: Set env.
        run: |
          echo "set env"

  bastion-deploy-mc:
    needs: set-env
    uses: "./.github/workflows/deploy_mc_bastion_function.yml"
    with:
      tenancy: "mc"
      subsystem: "common"
      aws-account: "mc-${{ needs.set-env.outputs.short-env }}"
      aws-region: ${{ needs.set-env.outputs.aws_region }}
      env: ${{ needs.set-env.outputs.env }}
      short-env: ${{ needs.set-env.outputs.short-env }}
    secrets:
      MC_DEPLOY_IAM_ROLE_ARN: ${{ secrets.MC_DEPLOY_IAM_ROLE_ARN }}
