name: "[_CD] Bastion deploy function"
concurrency:
  group: ${{ github.workflow }}-${{ inputs.subsystem }}-bastion-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: true

on:
  workflow_call:
    secrets:
      MC_DEPLOY_IAM_ROLE_ARN:
        required: true
        description: "The IAM role ARN to assume for deployment"
    inputs:
      tenancy:
        type: string
        required: true
        description: "The tenancy to deploy to."
      subsystem:
        type: string
        required: true
        description: "The subsystem to run the deploy for."
      aws-account:
        type: string
        required: true
        description: "The AWS account to deploy to."
      aws-region:
        type: string
        required: true
        description: "The AWS region to deploy to."
      env:
        type: string
        required: true
        description: "The environment to deploy to."
      short-env:
        type: string
        required: true
        description: "The short environment to deploy to."

jobs:
  bastion-deploy-function:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env == 'develop' && 'develop' || inputs.env == 'production' && 'production' || inputs.env == 'staging' && 'staging' || 'develop' }}
    env:
      ENV: ${{ inputs.env == 'develop' && 'develop' || inputs.env == 'production' && 'production' || inputs.env == 'staging' && 'staging' || 'develop' }}
    timeout-minutes: 60

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.MC_DEPLOY_IAM_ROLE_ARN }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to Amazon ECR (us-east-1)
        id: login-ecr-us-east-1
        uses: aws-actions/amazon-ecr-login@v2
        env:
          AWS_REGION: us-east-1
        with:
          registry-type: public

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to Amazon ECR (default region)
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ECRの更新
      - name: build and push Docker image app
        uses: docker/build-push-action@v6
        id: build-image-app
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.tenancy }}-${{ inputs.short-env }}-${{ inputs.subsystem }}-bastion
        with:
          push: true
          context: .
          file: docker/${{ inputs.subsystem }}/bastion/Dockerfile.${{ env.ENV }}
          platforms: linux/arm64
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          cache-from: |
            type=gha,scope=bastion-cache
          cache-to: |
            ${{ github.ref == 'refs/heads/develop' && 'type=gha,mode=max,scope=bastion-cache' || '' }}
          provenance: false

      - name: Get task-definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ inputs.tenancy }}-${{ inputs.short-env }}-${{ inputs.subsystem }}-bastion --query taskDefinition --output json > ./${{ inputs.tenancy }}-${{ inputs.short-env }}-${{ inputs.subsystem }}-bastion.json

      - name: Fill in the new image ID and REVISION tag in the Amazon ECS task definition for bastion container
        id: render-bastion-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.tenancy }}-${{ inputs.short-env }}-${{ inputs.subsystem }}-bastion
        with:
          task-definition: ./${{ inputs.tenancy }}-${{ inputs.short-env }}-${{ inputs.subsystem }}-bastion.json
          container-name: "bastion"
          image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          environment-variables: "REVISION=${{ github.sha }}"

      - name: update Amazon ECS task definition bastion
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-bastion-container.outputs.task-definition }}
          cluster: ${{ inputs.tenancy }}-${{ inputs.short-env }}-${{ inputs.subsystem }}-bastion
          propagate-tags: TASK_DEFINITION
